// index.js
import { TwitterApi } from "twitter-api-v2";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { execSync } from "child_process";
import dotenv from "dotenv";

dotenv.config();

// --- Twitter client setup ---
let twitterClient = null;
if (
  process.env.APP_KEY &&
  process.env.APP_SECRET &&
  process.env.ACCESS_TOKEN &&
  process.env.ACCESS_SECRET
) {
  twitterClient = new TwitterApi({
    appKey: process.env.APP_KEY,
    appSecret: process.env.APP_SECRET,
    accessToken: process.env.ACCESS_TOKEN,
    accessSecret: process.env.ACCESS_SECRET,
  });
} else {
  console.warn("⚠️ Twitter credentials missing; operating in dry-run mode.");
}

// --- Gemini client setup ---
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// --- List of stocks ---
const stocks = [
  "20 Microns Limited ",
  "360 ONE WAM LIMITED ",
  "3M India Limited ",
  "5Paisa Capital Limited ",
  "63 moons technologies limited ",
  "Aadhar Housing Finance Limited ",
  "Aarti Drugs Limited ",
  "Aarti Industries Limited ",
  "Aarti Pharmalabs Limited ",
  "Aavas Financiers Limited ",
  "ABB India Limited ",
  "Abbott India Limited ",
  "Aditya Birla Capital Limited ",
  "A B Cotspin India Limited ",
  "Allied Blenders and Distillers Limited ",
  "Aditya Birla Fashion and Retail Limited ",
  "A B Infrabuild Limited ",
  "Aditya Birla Lifestyle Brands Limited ",
  "Aditya Birla Real Estate Limited ",
  "Aditya Birla Sun Life AMC Limited ",
  "ACC Limited ",
  "Accelya Solutions India Limited ",
  "Action Construction Equipment Limited ",
  "Archean Chemical Industries Limited ",
  "Andhra Cements Limited ",
  "Acme Solar Holdings Limited ",
  "Acutaas Chemicals Limited ",
  "Adani Energy Solutions Limited ",
  "Adani Enterprises Limited ",
  "Adani Green Energy Limited ",
  "Adani Ports and Special Economic Zone Limited ",
  "Adani Power Limited ",
  "ADF Foods Limited ",
  "Ador Welding Limited ",
  "Allied Digital Services Limited ",
  "Advait Energy Transitions Limited ",
  "Advance Agrolife Limited ",
  "Advani Hotels & Resorts (India) Limited ",
  "Advent Hotels International Limited ",
  "Advanced Enzyme Technologies Limited ",
  "Aegis Logistics Limited ",
  "Aegis Vopak Terminals Limited ",
  "Aequs Limited ",
  "Aeroflex Enterprises Limited ",
  "Aeroflex Industries Limited ",
  "Aether Industries Limited ",
  "Afcons Infrastructure Limited ",
  "Affle 3i Limited ",
  "Abans Financial Services Limited ",
  "Agarwal Industrial Corporation Limited ",
  "Dr. Agarwal's Health Care Limited ",
  "AGI Greenpac Limited ",
  "Agi Infra Limited ",
  "Anlon Healthcare Limited ",
  "Ahluwalia Contracts (India) Limited ",
  "AIA Engineering Limited ",
  "Authum Investment & Infrastructure Limited ",
  "Ajanta Pharma Limited ",
  "Ajax Engineering Limited ",
  "Ajmera Realty & Infra India Limited ",
  "Akums Drugs and Pharmaceuticals Limited ",
  "Akzo Nobel India Limited ",
  "Alembic Limited ",
  "Algoquant Fintech Limited ",
  "Alicon Castalloy Limited ",
  "Alivus Life Sciences Limited ",
  "Alkem Laboratories Limited ",
  "Alkyl Amines Chemicals Limited ",
  "Allcargo Logistics Limited ",
  "Alldigi Tech Limited ",
  "All Time Plastics Limited ",
  "Alok Industries Limited ",
  "Amber Enterprises India Limited ",
  "Ambika Cotton Mills Limited ",
  "Ambuja Cements Limited ",
  "Amines & Plasticizers Limited ",
  "Amrutanjan Health Care Limited ",
  "Anand Rathi Wealth Limited ",
  "Anant Raj Limited ",
  "ANDHRA PAPER LIMITED ",
  "The Andhra Sugars Limited ",
  "Angel One Limited ",
  "Antelopus Selan Energy Limited ",
  "Anthem Biosciences Limited ",
  "Anuh Pharma Limited ",
  "The Anup Engineering Limited ",
  "Anupam Rasayan India Limited ",
  "Apar Industries Limited ",
  "Apcotex Industries Limited ",
  "Apex Frozen Foods Limited ",
  "APL Apollo Tubes Limited ",
  "Alembic Pharmaceuticals Limited ",
  "Apollo Micro Systems Limited ",
  "Apollo Hospitals Enterprise Limited ",
  "Apollo Pipes Limited ",
  "Apollo Tyres Limited ",
  "Aptech Limited ",
  "Aptus Value Housing Finance India Limited ",
  "Aqylon Nexus Limited ",
  "Amara Raja Energy & Mobility Limited ",
  "Arfin India Limited ",
  "Arihant Capital Markets Limited ",
  "Arihant Superstructures Limited ",
  "Arisinfra Solutions Limited ",
  "Arkade Developers Limited ",
  "Arman Financial Services Limited ",
  "Arrow Greentech Limited ",
  "Anand Rathi Share and Stock Brokers Limited ",
  "Arvind Limited ",
  "Arvind Fashions Limited ",
  "Arvind SmartSpaces Limited ",
  "Asahi India Glass Limited ",
  "Automotive Stampings and Assemblies Limited ",
  "Associated Alcohols & Breweries Ltd. ",
  "Ashapura Minechem Limited ",
  "Ashiana Housing Limited ",
  "Ashoka Buildcon Limited ",
  "Ashok Leyland Limited ",
  "Asian Energy Services Limited ",
  "Asian Hotels (North) Limited ",
  "Asian Paints Limited ",
  "Asian Granito India Limited ",
  "ASK Automotive Limited ",
  "Astec LifeSciences Limited ",
  "Aster DM Healthcare Limited ",
  "Astral Limited ",
  "Astra Microwave Products Limited ",
  "AstraZeneca Pharma India Limited ",
  "Adani Total Gas Limited ",
  "Ather Energy Limited ",
  "Allcargo Terminals Limited ",
  "Atlanta Electricals Limited ",
  "Atul Limited ",
  "Atul Auto Limited ",
  "AU Small Finance Bank Limited ",
  "Aurionpro Solutions Limited ",
  "Aurobindo Pharma Limited ",
  "Aurum PropTech Limited ",
  "Automotive Axles Limited ",
  "Avadh Sugar & Energy Limited ",
  "Avalon Technologies Limited ",
  "Avantel Limited ",
  "Avanti Feeds Limited ",
  "Aditya Vision Limited ",
  "AVT Natural Products Limited ",
  "Awfis Space Solutions Limited ",
  "Antony Waste Handling Cell Limited ",
  "AWL Agri Business Limited ",
  "Axis Bank Limited ",
  "AXISCADES Technologies Limited ",
  "Aye Finance Limited ",
  "AYM Syntex Limited ",
  "Azad Engineering Limited ",
  "Bajaj Auto Limited ",
  "Bajaj Consumer Care Limited ",
  "Bajaj Electricals Limited ",
  "Bajaj Finserv Limited ",
  "Bajaj Healthcare Limited ",
  "Bajaj Housing Finance Limited ",
  "Bajaj Hindusthan Sugar Limited ",
  "Bajaj Holdings & Investment Limited ",
  "Indef Manufacturing Limited ",
  "Bajel Projects Limited ",
  "Bajaj Finance Limited ",
  "Balaji Telefilms Limited ",
  "Balaji Amines Limited ",
  "Balkrishna Industries Limited ",
  "Balmer Lawrie & Company Limited ",
  "Balrampur Chini Mills Limited ",
  "Balu Forge Industries Limited ",
  "Bannari Amman Sugars Limited ",
  "Banco Products (I) Limited ",
  "Bandhan Bank Limited ",
  "Bank of Baroda ",
  "Bank of India ",
  "Bansal Wire Industries Limited ",
  "BASF India Limited ",
  "Bata India Limited ",
  "Bayer Cropscience Limited ",
  "Bharat Bijlee Limited ",
  "Black Box Limited ",
  "The Bombay Burmah Trading Corporation Limited ",
  "Brightcom Group Limited ",
  "Bcl Industries Limited ",
  "Bharat Dynamics Limited ",
  "Mrs. Bectors Food Specialities Limited ",
  "Bharat Electronics Limited ",
  "Belrise Industries Limited ",
  "BEML Limited ",
  "Bhansali Engineering Polymers Limited ",
  "Berger Paints (I) Limited ",
  "Beta Drugs Limited ",
  "BF Investment Limited ",
  "BGR Energy Systems Limited ",
  "Bhagiradha Chemicals & Industries Limited ",
  "Bhageria Industries Limited ",
  "Bharat Forge Limited ",
  "Bharat Rasayan Limited ",
  "Bharat Seats Limited ",
  "Bharat Wire Ropes Limited ",
  "Bharti Airtel Limited ",
  "Bharti Hexacom Limited ",
  "Bharat Heavy Electricals Limited ",
  "Bigbloc Construction Limited ",
  "Bikaji Foods International Limited ",
  "Bhartiya International Limited ",
  "Biocon Limited ",
  "Birla Corporation Limited ",
  "Aditya Birla Money Limited ",
  "BirlaNu Limited ",
  "BLACKBUCK LIMITED ",
  "BEML Land Assets Limited ",
  "Bliss GVS Pharma Limited ",
  "B. L. Kashyap and Sons Limited ",
  "BLS International Services Limited ",
  "BLS E-Services Limited ",
  "Blue Dart Express Limited ",
  "Blue Jet Healthcare Limited ",
  "Blue Star Limited ",
  "BlueStone Jewellery and Lifestyle Limited ",
  "Bluspring Enterprises Limited ",
  "BMW Ventures Limited ",
  "Bodal Chemicals Limited ",
  "Bombay Dyeing & Mfg Company Limited ",
  "Borosil Limited ",
  "BOROSIL RENEWABLES LIMITED ",
  "Borosil Scientific Limited ",
  "BOSCH HOME COMFORT INDIA LIMITED ",
  "Bosch Limited ",
  "Bharat Petroleum Corporation Limited ",
  "Brigade Enterprises Limited ",
  "Brigade Hotel Ventures Limited ",
  "Britannia Industries Limited ",
  "BSE Limited ",
  "Bombay Super Hybrid Seeds Limited ",
  "BIRLASOFT LIMITED ",
  "Shankara Buildpro Limited ",
  "Butterfly Gandhimathi Appliances Limited ",
  "Camlin Fine Sciences Limited ",
  "Campus Activewear Limited ",
  "Computer Age Management Services Limited ",
  "Canara Bank ",
  "Can Fin Homes Limited ",
  "Canara HSBC Life Insurance Company Limited ",
  "Cantabil Retail India Limited ",
  "Capacit'e Infraprojects Limited ",
  "Capillary Technologies India Limited ",
  "Capital Small Finance Bank Limited ",
  "Caplin Point Laboratories Limited ",
  "Carborundum Universal Limited ",
  "CARE Ratings Limited ",
  "Carraro India Limited ",
  "Cartrade Tech Limited ",
  "CARYSIL LIMITED ",
  "Castrol India Limited ",
  "AvenuesAI Limited ",
  "Consolidated Construction Consortium Limited ",
  "CCL Products (India) Limited ",
  "Central Depository Services (India) Limited ",
  "CEAT Limited ",
  "Ceigall India Limited ",
  "Cello World Limited ",
  "Cemindia Projects Limited ",
  "Century Enka Limited ",
  "Central Bank of India ",
  "Centrum Capital Limited ",
  "Centum Electronics Limited ",
  "Century Plyboards (India) Limited ",
  "Cera Sanitaryware Limited ",
  "CESC Limited ",
  "Concord Enviro Systems Limited ",
  "Capri Global Capital Limited ",
  "CG Power and Industrial Solutions Limited ",
  "Chalet Hotels Limited ",
  "Chambal Fertilizers & Chemicals Limited ",
  "Chemcon Speciality Chemicals Limited ",
  "Chemfab Alkalis Limited ",
  "Chemplast Sanmar Limited ",
  "Chennai Petroleum Corporation Limited ",
  "Cheviot Company Limited ",
  "Choice International Limited ",
  "Cholamandalam Investment and Finance Company Limited ",
  "Cholamandalam Financial Holdings Limited ",
  "CIE Automotive India Limited ",
  "Capital India Finance Limited ",
  "Cigniti Technologies Limited ",
  "Cipla Limited ",
  "Clean Science and Technology Limited ",
  "Chaman Lal Setia Exports Limited ",
  "CMS Info Systems Limited ",
  "Creative Newtech Limited ",
  "Coal India Limited ",
  "Cochin Shipyard Limited ",
  "Coffee Day Enterprises Limited ",
  "Coforge Limited ",
  "Cohance Lifesciences Limited ",
  "Colgate Palmolive (India) Limited ",
  "Commercial Syn Bags Limited ",
  "Container Corporation of India Limited ",
  "Concord Biotech Limited ",
  "Confidence Petroleum India Limited ",
  "Consolidated Finvest & Holdings Limited ",
  "Control Print Limited ",
  "Coromandel International Limited ",
  "COSMO FIRST LIMITED ",
  "Aditya Infotech Limited ",
  "Craftsman Automation Limited ",
  "Canara Robeco Asset Management Company Limited ",
  "CREDITACCESS GRAMEEN LIMITED ",
  "Crest Ventures Limited ",
  "CRISIL Limited ",
  "Crizac Limited ",
  "Crompton Greaves Consumer Electricals Limited ",
  "CSB Bank Limited ",
  "CSL Finance Limited ",
  "City Union Bank Limited ",
  "Cummins India Limited ",
  "Cupid Limited ",
  "Cyient Limited ",
  "Cyient DLM Limited ",
  "Dabur India Limited ",
  "Dalmia Bharat Limited ",
  "Dalmia Bharat Sugar and Industries Limited ",
  "Dam Capital Advisors Limited ",
  "Datamatics Global Services Limited ",
  "Data Patterns (India) Limited ",
  "Davangere Sugar Company Limited ",
  "D.B.Corp Limited ",
  "Dilip Buildcon Limited ",
  "Dhampur Bio Organics Limited ",
  "Valor Estate Limited ",
  "Dishman Carbogen Amcis Limited ",
  "DCB Bank Limited ",
  "DCM Shriram Limited ",
  "DCM Shriram Industries Limited ",
  "DCW Limited ",
  "DCX Systems Limited ",
  "Ddev Plastiks Industries Limited ",
  "Deccan Cements Limited ",
  "DEE Development Engineers Limited ",
  "Deepak Fertilizers and Petrochemicals Corporation Limited ",
  "Deepak Nitrite Limited ",
  "Deep Industries Limited ",
  "Delhivery Limited ",
  "Delta Corp Limited ",
  "Den Networks Limited ",
  "Denta Water and Infra Solutions Limited ",
  "Devyani International Limited ",
  "Dhampur Sugar Mills Limited ",
  "Dhanlaxmi Bank Limited ",
  "Dhanuka Agritech Limited ",
  "Dharmaj Crop Guard Limited ",
  "Dhunseri Investments Limited ",
  "Diamond Power Infrastructure Limited ",
  "Prataap Snacks Limited ",
  "DIC India Limited ",
  "Diffusion Engineers Limited ",
  "Digitide Solutions Limited ",
  "Dish TV India Limited ",
  "Divgi Torqtransfer Systems Limited ",
  "Divi's Laboratories Limited ",
  "Dixon Technologies (India) Limited ",
  "DLF Limited ",
  "D-Link (India) Limited ",
  "Avenue Supermarts Limited ",
  "DMCC SPECIALITY CHEMICALS LIMITED ",
  "Dodla Dairy Limited ",
  "Dolat Algotech Limited ",
  "Dollar Industries Limited ",
  "Dolphin Offshore Enterprises (India) Limited ",
  "DOMS Industries Limited ",
  "D. P. Abhushan Limited ",
  "DPSC Limited ",
  "Dredging Corporation of India Limited ",
  "Dr. Reddy's Laboratories Limited ",
  "Dynacons Systems & Solutions Limited ",
  "Dhunseri Ventures Limited ",
  "Dwarikesh Sugar Industries Limited ",
  "Dynamic Cables Limited ",
  "Dynamatic Technologies Limited ",
  "E2E Networks Limited ",
  "Easy Trip Planners Limited ",
  "GNG Electronics Limited ",
  "eClerx Services Limited ",
  "Ecos (India) Mobility & Hospitality Limited ",
  "Edelweiss Financial Services Limited ",
  "EFC (I) Limited ",
  "Eicher Motors Limited ",
  "EID Parry India Limited ",
  "Enviro Infra Engineers Limited ",
  "Euro India Fresh Foods Limited ",
  "EIH Associated Hotels Limited ",
  "EIH Limited ",
  "Eimco Elecon (India) Limited ",
  "Everest Kanto Cylinder Limited ",
  "Eldeco Housing And Industries Limited ",
  "Elecon Engineering Company Limited ",
  "Electrosteel Castings Limited ",
  "Electrotherm (India) Limited ",
  "Elgi Equipments Limited ",
  "Elin Electronics Limited ",
  "Ellenbarrie Industrial Gases Limited ",
  "Emami Limited ",
  "Emami Paper Mills Limited ",
  "Emcure Pharmaceuticals Limited ",
  "Electronics Mart India Limited ",
  "Emkay Global Financial Services Limited ",
  "Emmvee Photovoltaic Power Limited ",
  "EMS Limited ",
  "eMudhra Limited ",
  "Endurance Technologies Limited ",
  "Engineers India Limited ",
  "Entertainment Network (India) Limited ",
  "Siemens Energy India Limited ",
  "Entero Healthcare Solutions Limited ",
  "EPACK Durable Limited ",
  "EPack Prefab Technologies Limited ",
  "Epigral Limited ",
  "EPL Limited ",
  "Equitas Small Finance Bank Limited ",
  "Eris Lifesciences Limited ",
  "Esab India Limited ",
  "ESAF Small Finance Bank Limited ",
  "Escorts Kubota Limited ",
  "Essar Shipping Limited ",
  "Ester Industries Limited ",
  "ETERNAL LIMITED ",
  "Ethos Limited ",
  "Eureka Forbes Limited ",
  "Euro Pratik Sales Limited ",
  "Eveready Industries India Limited ",
  "Everest Industries Limited ",
  "Excel Industries Limited ",
  "Excelsoft Technologies Limited ",
  "Exicom Tele-Systems Limited ",
  "Exide Industries Limited ",
  "Expleo Solutions Limited ",
  "Fabtech Technologies Limited ",
  "Fertilizers and Chemicals Travancore Limited ",
  "Fairchem Organics Limited ",
  "Faze Three Limited ",
  "Fineotex Chemical Limited ",
  "FDC Limited ",
  "The Federal Bank  Limited ",
  "Fedbank Financial Services Limited ",
  "Fiem Industries Limited ",
  "Filatex India Limited ",
  "Finolex Cables Limited ",
  "Fine Organic Industries Limited ",
  "Finkurve Financial Services Limited ",
  "Fino Payments Bank Limited ",
  "Finolex Industries Limited ",
  "Brainbees Solutions Limited ",
  "Fischer Medical Ventures Limited ",
  "Five-Star Business Finance Limited ",
  "Flair Writing Industries Limited ",
  "Gujarat Fluorochemicals Limited ",
  "Federal-Mogul Goetze (India) Limited. ",
  "FORCE MOTORS LTD ",
  "Fortis Healthcare Limited ",
  "Foseco India Limited ",
  "Fractal Analytics Limited ",
  "Firstsource Solutions Limited ",
  "Fusion Finance Limited ",
  "Gabriel India Limited ",
  "Gujarat Ambuja Exports Limited ",
  "GAIL (India) Limited ",
  "Gala Precision Engineering Limited ",
  "Galaxy Surfactants Limited ",
  "Gallantt Ispat Limited ",
  "Gandhar Oil Refinery (India) Limited ",
  "Gandhi Special Tubes Limited ",
  "Ganesha Ecosphere Limited ",
  "Ganesh Benzoplast Limited ",
  "Ganesh Consumer Products Limited ",
  "GANESH HOUSING LIMITED ",
  "Garware Technical Fibres Limited ",
  "Garuda Construction and Engineering Limited ",
  "Gateway Distriparks Limited ",
  "GeeCee Ventures Limited ",
  "Gem Aromatics Limited ",
  "Genesys International Corporation Limited ",
  "Genus Power Infrastructures Limited ",
  "Geojit Financial Services Limited ",
  "The Great Eastern Shipping Company Limited ",
  "GFL Limited ",
  "GHCL Limited ",
  "GHCL Textiles Limited ",
  "GIC Housing Finance Limited ",
  "General Insurance Corporation of India ",
  "Gillette India Limited ",
  "Gujarat Industries Power Company Limited ",
  "GK Energy Limited ",
  "Gujarat Kidney And Super Speciality Limited ",
  "GKW Limited ",
  "Gland Pharma Limited ",
  "GlaxoSmithKline Pharmaceuticals Limited ",
  "Glenmark Pharmaceuticals Limited ",
  "Globus Spirits Limited ",
  "Gloster Limited ",
  "GM Breweries Limited ",
  "Gujarat Mineral Development Corporation Limited ",
  "GMM Pfaudler Limited ",
  "GMR AIRPORTS LIMITED ",
  "GMR Power and Urban Infra Limited ",
  "GNA Axles Limited ",
  "Gujarat Narmada Valley Fertilizers and Chemicals Limited ",
  "GOCL Corporation Limited ",
  "Go Fashion (India) Limited ",
  "Godavari Biorefineries Limited ",
  "Godfrey Phillips India Limited ",
  "Go Digit General Insurance Limited ",
  "Godrej Agrovet Limited ",
  "Godrej Consumer Products Limited ",
  "Godrej Industries Limited ",
  "Godrej Properties Limited ",
  "Gokaldas Exports Limited ",
  "Gokul Agro Resources Limited ",
  "Goldiam International Limited ",
  "Goodluck India Limited ",
  "Gopal Snacks Limited ",
  "Godawari Power And Ispat limited ",
  "Gujarat Pipavav Port Limited ",
  "GPT Healthcare Limited ",
  "GPT Infraprojects Limited ",
  "Granules India Limited ",
  "Graphite India Limited ",
  "Grasim Industries Limited ",
  "Gravita India Limited ",
  "Greaves Cotton Limited ",
  "Greenlam Industries Limited ",
  "Greenpanel Industries Limited ",
  "Greenply Industries Limited ",
  "Orient Green Power Company Limited ",
  "Grindwell Norton Limited ",
  "G R Infraprojects Limited ",
  "GRM Overseas Limited ",
  "Billionbrains Garage Ventures Limited ",
  "GRP Limited ",
  "Garden Reach Shipbuilders & Engineers Limited ",
  "Garware Hi-Tech Films Limited ",
  "Gujarat State Fertilizers & Chemicals Limited ",
  "Gujarat State Petronet Limited ",
  "GTL Infrastructure Limited ",
  "GTPL Hathway Limited ",
  "Gufic Biosciences Limited ",
  "Gujarat Alkalies and Chemicals Limited ",
  "Gujarat Gas Limited ",
  "Gujarat Themis Biosyn Limited ",
  "Gulf Oil Lubricants India Limited ",
  "Gulshan Polyols Limited ",
  "GE Power India Limited ",
  "GE Vernova T&D India Limited ",
  "Hindustan Aeronautics Limited ",
  "Happiest Minds Technologies Limited ",
  "Happy Forgings Limited ",
  "Hariom Pipe Industries Limited ",
  "Harsha Engineers International Limited ",
  "Hathway Cable & Datacom Limited ",
  "Hatsun Agro Product Limited ",
  "Havells India Limited ",
  "HBL Engineering Limited ",
  "Hindustan Construction Company Limited ",
  "Healthcare Global Enterprises Limited ",
  "HCL Technologies Limited ",
  "HDB Financial Services Limited ",
  "HDFC Asset Management Company Limited ",
  "HDFC Bank Limited ",
  "HDFC Life Insurance Company Limited ",
  "HEG Limited ",
  "HeidelbergCement India Limited ",
  "Hemisphere Properties India Limited ",
  "Heranba Industries Limited ",
  "Heritage Foods Limited ",
  "Hero MotoCorp Limited ",
  "Hester Biosciences Limited ",
  "Hexa Tradex Limited ",
  "Hexaware Technologies Limited ",
  "HFCL Limited ",
  "H.G. Infra Engineering Limited ",
  "Hinduja Global Solutions Limited ",
  "Hikal Limited ",
  "Himatsingka Seide Limited ",
  "Hindalco Industries Limited ",
  "Hindustan Composites Limited ",
  "Hindustan Copper Limited ",
  "Hindustan Oil Exploration Company Limited ",
  "Hindustan Petroleum Corporation Limited ",
  "Hindustan Unilever Limited ",
  "Hindware Home Innovation Limited ",
  "Hindustan Zinc Limited ",
  "Hind Rectifiers Limited ",
  "Hi-Tech Pipes Limited ",
  "HLE Glascoat Limited ",
  "HLV LIMITED ",
  "HMA Agro Industries Limited ",
  "Hindustan Media Ventures Limited ",
  "Hindustan Foods Limited ",
  "Home First Finance Company India Limited ",
  "Honasa Consumer Limited ",
  "Honeywell Automation India Limited ",
  "Honda India Power Products Limited ",
  "HPL Electric & Power Limited ",
  "Himadri Speciality Chemical Limited ",
  "HT Media Limited ",
  "Hubtown Limited ",
  "Housing & Urban Development Corporation Limited ",
  "Huhtamaki India Limited ",
  "Hyundai Motor India Limited ",
  "Indiabulls Limited ",
  "Ice Make Refrigeration Limited ",
  "ICICI Prudential Asset Management Company Limited ",
  "ICICI Bank Limited ",
  "ICICI Lombard General Insurance Company Limited ",
  "ICICI Prudential Life Insurance Company Limited ",
  "Indo Count Industries Limited ",
  "ICRA Limited ",
  "IDBI Bank Limited ",
  "Vodafone Idea Limited ",
  "Ideaforge Technology Limited ",
  "IDFC First Bank Limited ",
  "Indian Energy Exchange Limited ",
  "IFB Agro Industries Limited ",
  "IFB Industries Limited ",
  "IFCI Limited ",
  "IFGL Refractories Limited ",
  "Igarashi Motors India Limited ",
  "International Gemmological Institute (India) Limited ",
  "Indraprastha Gas Limited ",
  "IG Petrochemicals Limited ",
  "IIFL Finance Limited ",
  "IIFL Capital Services Limited ",
  "IKIO Technologies Limited ",
  "Inventurus Knowledge Solutions Limited ",
  "Imagicaaworld Entertainment Limited ",
  "Indian Metals & Ferro Alloys Limited ",
  "India Motor Parts and Accessories Limited ",
  "Indegene Limited ",
  "The Indian Hotels Company Limited ",
  "The India Cements Limited ",
  "India Glycols Limited ",
  "Indiamart Intermesh Limited ",
  "Indian Bank ",
  "Indian Hume Pipe Company Limited ",
  "India Shelter Finance Corporation Limited ",
  "InterGlobe Aviation Limited ",
  "Indigo Paints Limited ",
  "Indiqube Spaces Limited ",
  "India Nippon Electricals Limited ",
  "Indo Amines Limited ",
  "Indo Borax & Chemicals Limited ",
  "Indoco Remedies Limited ",
  "Indo Farm Equipment Limited ",
  "Indo Rama Synthetics (India) Limited ",
  "IndoStar Capital Finance Limited ",
  "Indo Tech Transformers Limited ",
  "Indo Thai Securities Limited ",
  "Indraprastha Medical Corporation Limited ",
  "Ind-Swift Laboratories Limited ",
  "IndusInd Bank Limited ",
  "Indus Towers Limited ",
  "InfoBeans Technologies Limited ",
  "Infosys Limited ",
  "Ingersoll Rand (India) Limited ",
  "Innova Captab Limited ",
  "Innovana Thinklabs Limited ",
  "Inox Green Energy Services Limited ",
  "INOX India Limited ",
  "Inox Wind Limited ",
  "Insecticides (India) Limited ",
  "Intellect Design Arena Limited ",
  "Interarch Building Solutions Limited ",
  "International Conveyors Limited ",
  "Indian Overseas Bank ",
  "Indian Oil Corporation Limited ",
  "IOL Chemicals and Pharmaceuticals Limited ",
  "ION Exchange (India) Limited ",
  "IPCA Laboratories Limited ",
  "India Pesticides Limited ",
  "IRB Infrastructure Developers Limited ",
  "Ircon International Limited ",
  "Indian Railway Catering And Tourism Corporation Limited ",
  "Indian Renewable Energy Development Agency Limited ",
  "Indian Railway Finance Corporation Limited ",
  "IRIS RegTech Solutions Limited ",
  "Iris Clothings Limited ",
  "IRM Energy Limited ",
  "Isgec Heavy Engineering Limited ",
  "ITC Limited ",
  "ITC Hotels Limited ",
  "India Tourism Development Corporation Limited ",
  "ITI Limited ",
  "Ivalue Infosolutions Limited ",
  "Le Travenues Technology Limited ",
  "IZMO Limited ",
  "The Jammu & Kashmir Bank Limited ",
  "Jagran Prakashan Limited ",
  "Jagsonpal Pharmaceuticals Limited ",
  "Jai Balaji Industries Limited ",
  "Jai Corp Limited ",
  "Jain Resource Recycling Limited ",
  "Jamna Auto Industries Limited ",
  "Jaro Institute of Technology Management and Research Limited ",
  "Jash Engineering Limited ",
  "Jayant Agro Organics Limited ",
  "Jay Bharat Maruti Limited ",
  "Jayaswal Neco Industries Limited ",
  "JB Chemicals & Pharmaceuticals Limited ",
  "JBM Auto Limited ",
  "J.G.Chemicals Limited ",
  "Jindal Photo Limited ",
  "Jindal Poly Films Limited ",
  "Jindal Saw Limited ",
  "JINDAL STEEL LIMITED ",
  "Jindal Drilling And Industries Limited ",
  "Jindal Worldwide Limited ",
  "Jio Financial Services Limited ",
  "Jain Irrigation Systems Limited ",
  "Jain Irrigation Systems Limited ",
  "JITF Infralogistics Limited ",
  "JK Cement Limited ",
  "J.Kumar Infraprojects Limited ",
  "JK Lakshmi Cement Limited ",
  "JK Paper Limited ",
  "JK Tyre & Industries Limited ",
  "Jupiter Life Line Hospitals Limited ",
  "JM Financial Limited ",
  "JNK India Limited ",
  "Jindal Poly Investment and Finance Company Limited ",
  "Jaiprakash Power Ventures Limited ",
  "Jana Small Finance Bank Limited ",
  "Jindal Stainless Limited ",
  "Jeena Sikho Lifecare Limited ",
  "JSW Cement Limited ",
  "JSW Energy Limited ",
  "JSW Holdings Limited ",
  "JSW Infrastructure Limited ",
  "JSW Steel Limited ",
  "Jtekt India Limited ",
  "JTL INDUSTRIES LIMITED ",
  "Jubilant Agri and Consumer Products Limited ",
  "Jubilant Foodworks Limited ",
  "Jubilant Ingrevia Limited ",
  "Jubilant Pharmova Limited ",
  "Juniper Hotels Limited ",
  "Just Dial Limited ",
  "Jupiter Wagons Limited ",
  "Jyothy Labs Limited ",
  "Jyoti CNC Automation Limited ",
  "Jyoti Structures Limited ",
  "Kabra Extrusion Technik Limited ",
  "Kajaria Ceramics Limited ",
  "Sai Silks (Kalamandir) Limited ",
  "Kalpataru Limited ",
  "Kalyan Jewellers India Limited ",
  "Kamat Hotels (I) Limited ",
  "Kamdhenu Limited ",
  "Kansai Nerolac Paints Limited ",
  "Karur Vysya Bank Limited ",
  "Kaynes Technology India Limited ",
  "KCP Limited ",
  "KDDL Limited ",
  "KEC International Limited ",
  "Kirloskar Electric Company Limited ",
  "KEI Industries Limited ",
  "Kellton Tech Solutions Limited ",
  "Kernex Microsystems (India) Limited ",
  "Kfin Technologies Limited ",
  "Khaitan Chemicals & Fertilizers Limited ",
  "Kalyani Investment Company Limited ",
  "Kilitch Drugs (India) Limited ",
  "Krishna Institute of Medical Sciences Limited ",
  "Kingfa Science & Technology (India) Limited ",
  "KIOCL Limited ",
  "Kiri Industries Limited ",
  "Kirloskar Brothers Limited ",
  "Kirloskar Oil Engines Limited ",
  "Kirloskar Industries Limited ",
  "Kirloskar Pneumatic Company Limited ",
  "Kitex Garments Limited ",
  "Kewal Kiran Clothing Limited ",
  "Knowledge Marine & Engineering Works Limited ",
  "KNR Constructions Limited ",
  "Kokuyo Camlin Limited ",
  "Kolte - Patil Developers Limited ",
  "Kopran Limited ",
  "Kotak Mahindra Bank Limited ",
  "Kothari Petrochemicals Limited ",
  "K.P. Energy Limited ",
  "KPI Green Energy Limited ",
  "Kalpataru Projects International Limited ",
  "KPIT Technologies Limited ",
  "K.P.R. Mill Limited ",
  "KRBL Limited ",
  "Krishana Phoschem Limited ",
  "Krishival Foods Limited ",
  "Krishna Defence And Allied Industries Limited ",
  "KRN Heat Exchanger and Refrigeration Limited ",
  "Kross Limited ",
  "Krsnaa Diagnostics Limited ",
  "Krystal Integrated Services Limited ",
  "Ksb Limited ",
  "Kaveri Seed Company Limited ",
  "KSH International Limited ",
  "Kalyani Steels Limited ",
  "Ksolves India Limited ",
  "The Karnataka Bank Limited ",
  "Kuantum Papers Limited ",
  "Dr. Lal Path Labs Ltd. ",
  "Landmark Cars Limited ",
  "La Opala RG Limited ",
  "Latent View Analytics Limited ",
  "Laurus Labs Limited ",
  "Laxmi Dental Limited ",
  "Laxmi India Finance Limited ",
  "Le Merite Exports Limited ",
  "Lemon Tree Hotels Limited ",
  "Lenskart Solutions Limited ",
  "LG Balakrishnan & Bros Limited ",
  "LG Electronics India Limited ",
  "Laxmi Goldorna House Limited ",
  "LIC Housing Finance Limited ",
  "Life Insurance Corporation Of India ",
  "Likhitha Infrastructure Limited ",
  "Linc Limited ",
  "Lincoln Pharmaceuticals Limited ",
  "Linde India Limited ",
  "LLOYDS ENGINEERING WORKS LIMITED ",
  "Lloyds Enterprises Limited ",
  "Lloyds Metals And Energy Limited ",
  "LMW Limited ",
  "Lodha Developers Limited ",
  "Sri Lotus Developers and Realty Limited ",
  "Larsen & Toubro Limited ",
  "L&T Finance Limited ",
  "LT Foods Limited ",
  "LTIMindtree Limited ",
  "L&T Technology Services Limited ",
  "Lumax Industries Limited ",
  "Lumax Auto Technologies Limited ",
  "Lupin Limited ",
  "Lux Industries Limited ",
  "Laxmi Organic Industries Limited ",
  "Mahindra & Mahindra Limited ",
  "Mahindra & Mahindra Financial Services Limited ",
  "Macpower CNC Machines Limited ",
  "Madras Fertilizers Limited ",
  "Magadh Sugar & Energy Limited ",
  "Bank of Maharashtra ",
  "Mahindra Lifespace Developers Limited ",
  "Mahindra Logistics Limited ",
  "Maharashtra Scooters Limited ",
  "Maharashtra Seamless Limited ",
  "Maithan Alloys Limited ",
  "Mallcom (India) Limited ",
  "Mamata Machinery Limited ",
  "Manaksia Coated Metals & Industries Limited ",
  "Manali Petrochemicals Limited ",
  "Manappuram Finance Limited ",
  "Manba Finance Limited ",
  "Mangalam Cement Limited ",
  "Man Industries (India) Limited ",
  "Man Infraconstruction Limited ",
  "Mankind Pharma Limited ",
  "Manorama Industries Limited ",
  "Vedant Fashions Limited ",
  "C.E. Info Systems Limited ",
  "Marathon Nextgen Realty Limited ",
  "Marico Limited ",
  "Marine Electricals (India) Limited ",
  "Marksans Pharma Limited ",
  "Maruti Suzuki India Limited ",
  "MAS Financial Services Limited ",
  "Mastek Limited ",
  "Master Trust Limited ",
  "Matrimony.Com Limited ",
  "Max Estates Limited ",
  "Max Healthcare Institute Limited ",
  "Max India Limited ",
  "Mayur Uniquoters Ltd ",
  "Mazagon Dock Shipbuilders Limited ",
  "Madhya Bharat Agro Products Limited ",
  "M & B Engineering Limited ",
  "Magellanic Cloud Limited ",
  "Multi Commodity Exchange of India Limited ",
  "Global Health Limited ",
  "Medi Assist Healthcare Services Limited ",
  "Medplus Health Services Limited ",
  "Meesho Limited ",
  "Mangal Electrical Industries Limited ",
  "Menon Bearings Limited ",
  "Metro Brands Limited ",
  "Metropolis Healthcare Limited ",
  "Max Financial Services Limited ",
  "Mahanagar Gas Limited ",
  "Mahindra Holidays & Resorts India Limited ",
  "MIC Electronics Limited ",
  "Mishra Dhatu Nigam Limited ",
  "Midwest Limited ",
  "Minda Corporation Limited ",
  "Mindteck (India) Limited ",
  "MIRC Electronics Limited ",
  "MM Forgings Limited ",
  "MMP Industries Limited ",
  "MMTC Limited ",
  "One Mobikwik Systems Limited ",
  "Modis Navnirman Limited ",
  "MOIL Limited ",
  "Meghmani Organics Limited ",
  "Mold-Tek Packaging Limited ",
  "Monarch Networth Capital Limited ",
  "Monte Carlo Fashions Limited ",
  "Morepen Laboratories Limited ",
  "Moschip Technologies Limited ",
  "Samvardhana Motherson International Limited ",
  "Motilal Oswal Financial Services Limited ",
  "Motisons Jewellers Limited ",
  "MphasiS Limited ",
  "MPS Limited ",
  "MRF Limited ",
  "Mangalore Refinery and Petrochemicals Limited ",
  "MSP Steel & Power Limited ",
  "Mstc Limited ",
  "Motherson Sumi Wiring India Limited ",
  "Mtar Technologies Limited ",
  "Mahanagar Telephone Nigam Limited ",
  "Mufin Green Finance Limited ",
  "Credo Brands Marketing Limited ",
  "Mukand Limited ",
  "Mukka Proteins Limited ",
  "Munjal Auto Industries Limited ",
  "Munjal Showa Limited ",
  "Muthoot Finance Limited ",
  "Muthoot Microfin Limited ",
  "Manoj Vaibhav Gems N Jewellers Limited ",
  "Mangalam Worldwide Limited ",
  "NACL Industries Limited ",
  "Nahar Poly Films Limited ",
  "Nahar Spinning Mills Limited ",
  "Nippon Life India Asset Management Limited ",
  "Natco Pharma Limited ",
  "National Aluminium Company Limited ",
  "Info Edge (India) Limited ",
  "NAVA LIMITED ",
  "Navin Fluorine International Limited ",
  "Navkar Corporation Limited ",
  "Navneet Education Limited ",
  "Nazara Technologies Limited ",
  "NBCC (India) Limited ",
  "N. B. I. Industrial Finance Company Limited ",
  "NCC Limited ",
  "NCL Industries Limited ",
  "Ndr Auto Components Limited ",
  "New Delhi Television Limited ",
  "Nelcast Limited ",
  "NELCO Limited ",
  "Neogen Chemicals Limited ",
  "Nephrocare Health Services Limited ",
  "Nesco Limited ",
  "Nestle India Limited ",
  "Netweb Technologies India Limited ",
  "Network18 Media & Investments Limited ",
  "Neuland Laboratories Limited ",
  "Newgen Software Technologies Limited ",
  "National Fertilizers Limited ",
  "NGL Fine-Chem Limited ",
  "Narayana Hrudayalaya Ltd. ",
  "NHPC Limited ",
  "The New India Assurance Company Limited ",
  "NIBE Limited ",
  "NIIT Limited ",
  "NIIT Learning Systems Limited ",
  "Nila Spaces Limited ",
  "Nilkamal Limited ",
  "NINtec Systems Limited ",
  "Nitco Limited ",
  "Nitin Spinners Limited ",
  "Niva Bupa Health Insurance Company Limited ",
  "NLC India Limited ",
  "NMDC Limited ",
  "NOCIL Limited ",
  "Northern Arc Capital Limited ",
  "Network People Services Technologies Limited ",
  "N R Agarwal Industries Limited ",
  "NRB Bearing Limited ",
  "Nalwa Sons Investments Limited ",
  "NMDC Steel Limited ",
  "NTPC Limited ",
  "NTPC Green Energy Limited ",
  "Nucleus Software Exports Limited ",
  "Nuvama Wealth Management Limited ",
  "Nuvoco Vistas Corporation Limited ",
  "FSN E-Commerce Ventures Limited ",
  "Oriental Aromatics Limited ",
  "Oberoi Realty Limited ",
  "Oracle Financial Services Software Limited ",
  "Oil India Limited ",
  "Ola Electric Mobility Limited ",
  "Olectra Greentech Limited ",
  "Omaxe Limited ",
  "OM INFRA LIMITED ",
  "One Point One Solutions Limited ",
  "Onesource Specialty Pharma Limited ",
  "Oil & Natural Gas Corporation Limited ",
  "OnMobile Global Limited ",
  "Onward Technologies Limited ",
  "Optiemus Infracom Limited ",
  "Orchid Pharma Limited ",
  "Oricon Enterprises Limited ",
  "Orient Cement Limited ",
  "Orient Electric Limited ",
  "Oriental Hotels Limited ",
  "Orient Technologies Limited ",
  "The Orissa Minerals Development Company Limited ",
  "Orkla India Limited ",
  "Oswal Agro Mills Limited ",
  "Oswal Greentech Limited ",
  "Oswal Pumps Limited ",
  "Pace Digitek Limited ",
  "Page Industries Limited ",
  "Paisalo Digital Limited ",
  "Panacea Biotec Limited ",
  "Panache Digilife Limited ",
  "Panama Petrochem Limited ",
  "Paramount Communications Limited ",
  "Paradeep Phosphates Limited ",
  "Parag Milk Foods Limited ",
  "Paras Defence and Space Technologies Limited ",
  "Park Medi World Limited ",
  "Apeejay Surrendra Park Hotels Limited ",
  "Pashupati Cotspin Limited ",
  "Patanjali Foods Limited ",
  "Patel Engineering Limited ",
  "Patel Retail Limited ",
  "One 97 Communications Limited ",
  "PCBL Chemical Limited ",
  "PC Jeweller Limited ",
  "Pudumjee Paper Products Limited ",
  "PDS Limited ",
  "Pennar Industries Limited ",
  "Peninsula Land Limited ",
  "Persistent Systems Limited ",
  "Petronet LNG Limited ",
  "Power Finance Corporation Limited ",
  "Pfizer Limited ",
  "Prime Focus Limited ",
  "PTC India Financial Services Limited ",
  "PG Electroplast Limited ",
  "Procter & Gamble Hygiene and Health Care Limited ",
  "Procter & Gamble Health Limited ",
  "Pearl Global Industries Limited ",
  "The Phoenix Mills Limited ",
  "Piccadily Agro Industries Limited ",
  "Pidilite Industries Limited ",
  "PI Industries Limited ",
  "Pilani Investment and Industries Corporation Limited ",
  "Pine Labs Limited ",
  "Piramal Finance Limited ",
  "Pitti Engineering Limited ",
  "Pix Transmissions Limited ",
  "Platinum Industries Limited ",
  "Punjab National Bank ",
  "PNB Gilts Limited ",
  "PNB Housing Finance Limited ",
  "PNC Infratech Limited ",
  "P N Gadgil Jewellers Limited ",
  "Pondy Oxides & Chemicals Limited ",
  "Pokarna Limited ",
  "PB Fintech Limited ",
  "Polycab India Limited ",
  "Poly Medicure Limited ",
  "Polyplex Corporation Limited ",
  "Poonawalla Fincorp Limited ",
  "Power Grid Corporation of India Limited ",
  "Hitachi Energy India Limited ",
  "Power Mech Projects Limited ",
  "Piramal Pharma Limited ",
  "Prabha Energy Limited ",
  "Praj Industries Limited ",
  "Prakash Industries Limited ",
  "Precision Camshafts Limited ",
  "Precision Wires India Limited ",
  "Premier Explosives Limited ",
  "Premier Energies Limited ",
  "Premier Polyfilm Limited ",
  "Prestige Estates Projects Limited ",
  "Pricol Limited ",
  "Prime Securities Limited ",
  "Prince Pipes And Fittings Limited ",
  "Privi Speciality Chemicals Limited ",
  "Prostarm Info Systems Limited ",
  "Protean eGov Technologies Limited ",
  "Prozone Realty Limited ",
  "Prism Johnson Limited ",
  "Prudent Corporate Advisory Services Limited ",
  "Punjab & Sind Bank ",
  "PSP Projects Limited ",
  "PTC India Limited ",
  "PTC Industries Limited ",
  "PTL Enterprises Limited ",
  "Punjab Chemicals & Crop Protection Limited ",
  "Puravankara Limited ",
  "PVP Ventures Limited ",
  "PVR INOX Limited ",
  "Popular Vehicles and Services Limited ",
  "Physicswallah Limited ",
  "Pyramid Technoplast Limited ",
  "Quality Power Electrical Equipments Limited ",
  "Quadrant Future Tek Limited ",
  "Quess Corp Limited ",
  "Quick Heal Technologies Limited ",
  "RACL Geartech Limited ",
  "Radhika Jeweltech Limited ",
  "Radico Khaitan Limited ",
  "Railtel Corporation Of India Limited ",
  "Rain Industries Limited ",
  "Rainbow Childrens Medicare Limited ",
  "Rajoo Engineers Limited ",
  "Rajratan Global Wire Limited ",
  "Rallis India Limited ",
  "Rama Steel Tubes Limited ",
  "The Ramco Cements Limited ",
  "Ramco Industries Limited ",
  "Ramco Systems Limited ",
  "Ramky Infrastructure Limited ",
  "Ram Ratna Wires Limited ",
  "Rane Holdings Limited ",
  "Rategain Travel Technologies Limited ",
  "Ratnamani Metals & Tubes Limited ",
  "Ratnaveer Precision Engineering Limited ",
  "Raymond Limited ",
  "Raymond Lifestyle Limited ",
  "Raymond Realty Limited ",
  "Restaurant Brands Asia Limited ",
  "RBL Bank Limited ",
  "RBZ Jewellers Limited ",
  "Rashtriya Chemicals and Fertilizers Limited ",
  "REC Limited ",
  "Redington Limited ",
  "Redtape Limited ",
  "Refex Industries Limited ",
  "Regaal Resources Limited ",
  "Relaxo Footwears Limited ",
  "Reliance Industries Limited ",
  "Religare Enterprises Limited ",
  "Ravindra Energy Limited ",
  "Shree Renuka Sugars Limited ",
  "Repco Home Finance Limited ",
  "Repro India Limited ",
  "Responsive Industries Limited ",
  "Renaissance Global Limited ",
  "Rhetan TMT Limited ",
  "RHI MAGNESITA INDIA LIMITED ",
  "Rico Auto Industries Limited ",
  "Reliance Industrial Infrastructure Limited ",
  "Rishabh Instruments Limited ",
  "Ritco Logistics Limited ",
  "RITES Limited ",
  "Ramkrishna Forgings Limited ",
  "R K Swamy Limited ",
  "R M Drip and Sprinklers Systems Limited ",
  "Rane (Madras) Limited ",
  "R&B Denims Limited ",
  "Royal Orchid Hotels Limited ",
  "Rolex Rings Limited ",
  "Rossari Biotech Limited ",
  "Rossell Techsys Limited ",
  "Roto Pumps Limited ",
  "ROUTE MOBILE LIMITED ",
  "Raghav Productivity Enhancers Limited ",
  "RPG Life Sciences Limited ",
  "Reliance Power Limited ",
  "RPSG VENTURES LIMITED ",
  "Rashi Peripherals Limited ",
  "R R Kabel Limited ",
  "RSWM Limited ",
  "R Systems International Limited ",
  "RattanIndia Enterprises Limited ",
  "RattanIndia Power Limited ",
  "Rubicon Research Limited ",
  "The Ruby Mills Limited ",
  "Rupa & Company Limited ",
  "Rushil Decor Limited ",
  "Keystone Realtors Limited ",
  "Rail Vikas Nigam Limited ",
  "Saatvik Green Energy Limited ",
  "Safari Industries (India) Limited ",
  "Sagar Cements Limited ",
  "SAGILITY LIMITED ",
  "Steel Authority of India Limited ",
  "Sai Life Sciences Limited ",
  "Sakar Healthcare Limited ",
  "Saksoft Limited ",
  "Salasar Techno Engineering Limited ",
  "Salzer Electronics Limited ",
  "Sambhv Steel Tubes Limited ",
  "Samhi Hotels Limited ",
  "Sammaan Capital Limited ",
  "Sanathan Textiles Limited ",
  "The Sandesh Limited ",
  "Sandhar Technologies Limited ",
  "Sandur Manganese & Iron Ores Limited ",
  "Sangam (India) Limited ",
  "Sanghi Industries Limited ",
  "Sanghvi Movers Limited ",
  "Sanofi India Limited ",
  "Sanofi Consumer Healthcare India Limited ",
  "Sansera Engineering Limited ",
  "Sanstar Limited ",
  "Sapphire Foods India Limited ",
  "Sarda Energy & Minerals Limited ",
  "Saregama India Limited ",
  "Sarla Performance Fibers Limited ",
  "Sasken Technologies Limited ",
  "Sastasundar Ventures Limited ",
  "Satia Industries Limited ",
  "Satin Creditcare Network Limited ",
  "Saurashtra Cement Limited ",
  "SBC Exports Limited ",
  "Shivalik Bimetal Controls Limited ",
  "SBFC Finance Limited ",
  "Suratwwala Business Group Limited ",
  "SBI Cards and Payment Services Limited ",
  "SBI Life Insurance Company Limited ",
  "State Bank of India ",
  "Schaeffler India Limited ",
  "S Chand And Company Limited ",
  "Schneider Electric Infrastructure Limited ",
  "Shipping Corporation Of India Limited ",
  "Shipping Corporation of India Land and Assets Limited ",
  "Scoda Tubes Limited ",
  "Som Distilleries & Breweries Limited ",
  "Seamec Limited ",
  "Sejal Glass Limited ",
  "Senco Gold Limited ",
  "Senores Pharmaceuticals Limited ",
  "SEPC Limited ",
  "Servotech Renewable Power System Limited ",
  "Seshasayee Paper and Boards Limited ",
  "Standard Engineering Technology Limited ",
  "Sheela Foam Limited ",
  "SG Finserve Limited ",
  "Synergy Green Industries Limited ",
  "SG Mart Limited ",
  "Shadowfax Technologies Limited ",
  "Shaily Engineering Plastics Limited ",
  "Shakti Pumps (India) Limited ",
  "Shalby Limited ",
  "Shanthi Gears Limited ",
  "Shanti Gold International Limited ",
  "Sharda Cropchem Limited ",
  "Sharda Motor Industries Limited ",
  "Share India Securities Limited ",
  "Shilchar Technologies Limited ",
  "Shilpa Medicare Limited ",
  "S H Kelkar and Company Limited ",
  "Shoppers Stop Limited ",
  "Shree Digvijay Cement Co.Ltd ",
  "SHREE CEMENT LIMITED ",
  "Shreeji Shipping Global Limited ",
  "Shree Pushkar Chemicals & Fertilisers Limited ",
  "Shree Rama Multi-Tech Limited ",
  "Shringar House of Mangalsutra Limited ",
  "Shriram Pistons & Rings Limited ",
  "Shriram Finance Limited ",
  "Shriram Properties Limited ",
  "Shyam Metalics and Energy Limited ",
  "Siemens Limited ",
  "Sigachi Industries Limited ",
  "SIGMA ADVANCED SYSTEMS LIMITED ",
  "Signatureglobal (India) Limited ",
  "Signpost India Limited ",
  "Silver Touch Technologies Limited ",
  "Simplex Infrastructures Limited ",
  "Sindhu Trade Links Limited ",
  "Sirca Paints India Limited ",
  "SIS LIMITED ",
  "Siyaram Silk Mills Limited ",
  "S.J.S. Enterprises Limited ",
  "SJVN Limited ",
  "SKF India Limited ",
  "SKF India (Industrial) Limited ",
  "Skipper Limited ",
  "SKM Egg Products Export (India) Limited ",
  "SKY GOLD AND DIAMONDS LIMITED ",
  "Smartworks Coworking Spaces Limited ",
  "SMC Global Securities Limited ",
  "SML Mahindra Limited ",
  "SMS Pharmaceuticals Limited ",
  "Snowman Logistics Limited ",
  "Sobha Limited ",
  "Solara Active Pharma Sciences Limited ",
  "Solar Industries India Limited ",
  "Solarworld Energy Solutions Limited ",
  "Solex Energy Limited ",
  "Somany Ceramics Limited ",
  "Sona BLW Precision Forgings Limited ",
  "Sonata Software Limited ",
  "Savita Oil Technologies Limited ",
  "The South Indian Bank Limited ",
  "S. P. Apparels Limited ",
  "Spandana Sphoorty Financial Limited ",
  "Sun Pharma Advanced Research Company Limited ",
  "Spectrum Electrical Industries Limited ",
  "Southern Petrochemicals Industries Corporation  Limited ",
  "Supreme Petrochem Limited ",
  "SPML Infra Limited ",
  "Sportking India Limited ",
  "SRF Limited ",
  "Sree Rayalaseema Hi-Strength Hypo Limited ",
  "SRM Contractors Limited ",
  "Steel Strips Wheels Limited ",
  "Stallion India Fluorochemicals Limited ",
  "Stanley Lifestyles Limited ",
  "Strides Pharma Science Limited ",
  "Star Cement Limited ",
  "Star Health and Allied Insurance Company Limited ",
  "The State Trading Corporation of India Limited ",
  "Steelcast Limited ",
  "STEEL EXCHANGE INDIA LIMITED ",
  "Stel Holdings Limited ",
  "Sterling Tools Limited ",
  "STL Networks Limited ",
  "Sterlite Technologies Limited ",
  "Stove Kraft Limited ",
  "Studds Accessories Limited ",
  "Seshaasai Technologies Limited ",
  "Stylam Industries Limited ",
  "Baazar Style Retail Limited ",
  "Styrenix Performance Materials Limited ",
  "Subex Limited ",
  "Subros Limited ",
  "Sudarshan Colorants India Limited ",
  "Sudarshan Chemical Industries Limited ",
  "Sudeep Pharma Limited ",
  "Sukhjit Starch & Chemicals Limited ",
  "Sula Vineyards Limited ",
  "Sumeet Industries Limited ",
  "Sumitomo Chemical India Limited ",
  "Summit Securities Limited ",
  "Sundaram Clayton Limited ",
  "Sundaram Finance Limited ",
  "Sundram Fasteners Limited ",
  "Sundrop Brands Limited ",
  "Sunflag Iron And Steel Company Limited ",
  "Sun Pharmaceutical Industries Limited ",
  "Sunteck Realty Limited ",
  "Sun TV Network Limited ",
  "Suprajit Engineering Limited ",
  "Supreme Industries Limited ",
  "Supriya Lifescience Limited ",
  "Suraj Estate Developers Limited ",
  "Suraksha Diagnostic Limited ",
  "Surya Roshni Limited ",
  "Suryoday Small Finance Bank Limited ",
  "Sutlej Textiles and Industries Limited ",
  "Suven Life Sciences Limited ",
  "Suyog Telematics Limited ",
  "Suzlon Energy Limited ",
  "Shree Vasu Logistics Limited ",
  "SWAN CORP LIMITED ",
  "Swaraj Engines Limited ",
  "Swelect Energy Systems Limited ",
  "Swiggy Limited ",
  "Sterling and Wilson Renewable Energy Limited ",
  "Symphony Limited ",
  "Syncom Formulations (India) Limited ",
  "Syngene International Limited ",
  "Syrma SGS Technology Limited ",
  "Systematix Corporate Services Limited ",
  "Taj GVK Hotels & Resorts Limited ",
  "Talbros Automotive Components Limited ",
  "Tanla Platforms Limited ",
  "Tara Chand InfraLogistic Solutions Limited ",
  "TARC Limited ",
  "Transformers And Rectifiers (India) Limited ",
  "Tarsons Products Limited ",
  "Tasty Bite Eatables Limited ",
  "Tata Capital Limited ",
  "Tata Chemicals Limited ",
  "Tata Communications Limited ",
  "TATA CONSUMER PRODUCTS LIMITED ",
  "Tata Elxsi Limited ",
  "Tata Investment Corporation Limited ",
  "Tata Power Company Limited ",
  "Tata Steel Limited ",
  "Tata Technologies Limited ",
  "Tatva Chintan Pharma Chem Limited ",
  "TBO Tek Limited ",
  "Tribhovandas Bhimji Zaveri Limited ",
  "Transport Corporation of India Limited ",
  "TCI Express Limited ",
  "TCPL Packaging Limited ",
  "Tata Consultancy Services Limited ",
  "TD Power Systems Limited ",
  "Teamlease Services Limited ",
  "Tech Mahindra Limited ",
  "Techno Electric & Engineering Company Limited ",
  "Tega Industries Limited ",
  "Tejas Networks Limited ",
  "Tembo Global Industries Limited ",
  "Tera Software Limited ",
  "Texmaco Infrastructure & Holdings Limited ",
  "Texmaco Rail & Engineering Limited ",
  "Tourism Finance Corporation of India Limited ",
  "Thangamayil Jewellery Limited ",
  "The Investment Trust Of India Limited ",
  "Thejo Engineering Limited ",
  "Leela Palaces Hotels & Resorts Limited ",
  "Themis Medicare Limited ",
  "Thermax Limited ",
  "Thomas Cook  (India)  Limited ",
  "Thyrocare Technologies Limited ",
  "Tilaknagar Industries Limited ",
  "Technocraft Industries (India) Limited ",
  "Tube Investments of India Limited ",
  "TIL Limited ",
  "Time Technoplast Limited ",
  "Timken India Limited ",
  "Tinna Rubber and Infrastructure Limited ",
  "Tips Music Limited ",
  "Thirumalai Chemicals Limited ",
  "TITAGARH RAIL SYSTEMS LIMITED ",
  "Titan Company Limited ",
  "Tamilnad Mercantile Bank Limited ",
  "Tata Motors Limited ",
  "Tata Motors Passenger Vehicles Limited ",
  "Tamilnadu PetroProducts Limited ",
  "Tamil Nadu Newsprint & Papers Limited ",
  "Torrent Pharmaceuticals Limited ",
  "Torrent Power Limited ",
  "TPL Plastech Limited ",
  "Transrail Lighting Limited ",
  "Travel Food Services Limited ",
  "Transindia Real Estate Limited ",
  "Trent Limited ",
  "Trident Limited ",
  "Triveni Turbine Limited ",
  "Triveni Engineering & Industries Limited ",
  "TruAlt Bioenergy Limited ",
  "TSF INVESTMENTS LIMITED ",
  "TTK Healthcare Limited ",
  "TTK Prestige Limited ",
  "Tata Teleservices (Maharashtra) Limited ",
  "TVS Holdings Limited ",
  "TVS Motor Company Limited ",
  "TVS Supply Chain Solutions Limited ",
  "TVS Srichakra Limited ",
  "TV Today Network Limited ",
  "United Breweries Limited ",
  "UCO Bank ",
  "Updater Services Limited ",
  "Ujaas Energy Limited ",
  "United Foodbrands Limited ",
  "UFLEX Limited ",
  "Ugro Capital Limited ",
  "Ujjivan Small Finance Bank Limited ",
  "UltraTech Cement Limited ",
  "Unichem Laboratories Limited ",
  "Unicommerce Esolutions Limited ",
  "Uniphos Enterprises Limited ",
  "Unimech Aerospace and Manufacturing Limited ",
  "Union Bank of India ",
  "Uniparts India Limited ",
  "United Spirits Limited ",
  "Unitech Limited ",
  "United Polyfab Gujarat Limited ",
  "Universal Cables Limited ",
  "UNO Minda Limited ",
  "UPL Limited ",
  "Urban Company Limited ",
  "Urja Global Limited ",
  "Usha Martin Limited ",
  "UTI Asset Management Company Limited ",
  "Utkarsh Small Finance Bank Limited ",
  "Fujiyama Power Systems Limited ",
  "Uttam Sugar Mills Limited ",
  "V2 Retail Limited ",
  "Vadilal Industries Limited ",
  "Vaibhav Global Limited ",
  "Vakrangee Limited ",
  "Valiant Organics Limited ",
  "Varroc Engineering Limited ",
  "Vascon Engineers Limited ",
  "Varun Beverages Limited ",
  "Vedanta Limited ",
  "Veedol Corporation Limited ",
  "Venky's (India) Limited ",
  "Ventive Hospitality Limited ",
  "Venus Pipes & Tubes Limited ",
  "Veranda Learning Solutions Limited ",
  "Vesuvius India Limited ",
  "V-Guard Industries Limited ",
  "Vardhman Holdings Limited ",
  "Vidhi Specialty Food Ingredients Limited ",
  "Vidya Wires Limited ",
  "Vijaya Diagnostic Centre Limited ",
  "Vikram Solar Limited ",
  "Vikran Engineering Limited ",
  "Vimta Labs Limited ",
  "Vinati Organics Limited ",
  "Vintage Coffee And Beverages Limited ",
  "Vindhya Telelinks Limited ",
  "VIP Industries Limited ",
  "Visaka Industries Limited ",
  "Vishnu Chemicals Limited ",
  "Viyash Scientific Limited ",
  "VLS Finance Limited ",
  "V-Mart Retail Limited ",
  "Vishal Mega Mart Limited ",
  "Voltamp Transformers Limited ",
  "Voltas Limited ",
  "Vishnu Prakash R Punglia Limited ",
  "VRL Logistics Limited ",
  "Vardhman Special Steels Limited ",
  "VST Industries Limited ",
  "V.S.T Tillers Tractors Limited ",
  "Vardhman Textiles Limited ",
  "Waaree Energies Limited ",
  "Waaree Renewable Technologies Limited ",
  "VA Tech Wabag Limited ",
  "Wakefit Innovations Limited ",
  "Walchandnagar Industries Limited ",
  "Wanbury Limited ",
  "Western Carriers (India) Limited ",
  "Wealth First Portfolio Managers Limited ",
  "Websol Energy System Limited ",
  "Wonder Electricals Limited ",
  "Welspun Corp Limited ",
  "Welspun Enterprises Limited ",
  "Welspun Living Limited ",
  "Wendt (India) Limited ",
  "WESTLIFE FOODWORLD LIMITED ",
  "WeWork India Management Limited ",
  "Wheels India Limited ",
  "Whirlpool of India Limited ",
  "Windlas Biotech Limited ",
  "Windsor Machines Limited ",
  "Wipro Limited ",
  "Wockhardt Limited ",
  "Wonderla Holidays Limited ",
  "West Coast Paper Mills Limited ",
  "Xchanging Solutions Limited ",
  "Xpro India Limited ",
  "Yasho Industries Limited ",
  "Yatharth Hospital & Trauma Care Services Limited ",
  "Yatra Online Limited ",
  "Yes Bank Limited ",
  "Yuken India Limited ",
  "Zaggle Prepaid Ocean Services Limited ",
  "Zee Entertainment Enterprises Limited ",
  "Zee Media Corporation Limited ",
  "Zensar Technologies Limited ",
  "Zen Technologies Limited ",
  "ZF Commercial Vehicle Control Systems India Limited ",
  "Zota Health Care LImited ",
  "Zuari Agro Chemicals Limited ",
  "ZUARI INDUSTRIES LIMITED ",
  "Zydus Lifesciences Limited ",
  "Zydus Wellness Limited ",
];

// --- Persistent index for cycling through stocks ---
let currentIndex = 0;

// --- Helper to get a random stock each time ---
function getNextStock() {
  if (!stocks || stocks.length === 0) throw new Error("Stocks array is empty");
  const index = Math.floor(Math.random() * stocks.length);
  const stock = stocks[index];
  console.log(`🎲 Randomly selected stock #${index}: ${stock}`);
  return stock;
}

// --- Retry wrapper for Gemini calls ---
async function generateTweet(prompt, retries = 3, delayMs = 40000) {
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const result = await model.generateContent(prompt);
    return result.response.text();
  } catch (err) {
    if ((err.message.includes("429") || err.message.includes("quota")) && retries > 0) {
      console.log(`Rate limited. Retrying in ${delayMs / 1000}s...`);
      await new Promise((r) => setTimeout(r, delayMs));
      return generateTweet(prompt, retries - 1, delayMs);
    }
    throw err;
  }
}

// --- Helper: split Gemini response into tweet-sized posts ---
function splitIntoPosts(text) {
  if (!text) return [];

  return text
    .split(/\n(?=Post\s*\d+:)/i)
    .map(p => p.replace(/^Post\s*\d+:\s*/i, "").trim())
    .filter(Boolean);
}

function splitByWords(text, maxLen = 270) {
  const words = text.split(" ");
  const chunks = [];
  let current = "";

  for (const word of words) {
    if ((current + " " + word).length > maxLen) {
      chunks.push(current.trim());
      current = word;
    } else {
      current += " " + word;
    }
  }

  if (current.trim()) chunks.push(current.trim());
  return chunks;
}

// --- Tweet sending function with max-length enforcement ---
async function sendTweet(tweetText, replyToId = null) {
  try {
    if (!tweetText) throw new Error("Empty tweet text");

    console.log("Generated Tweet:", tweetText);

    const tweetData = replyToId
      ? { reply: { in_reply_to_tweet_id: replyToId } }
      : {};

    const dryRunEnv = process.env.DRY_RUN?.toLowerCase() !== "false";
    const canPost = twitterClient && !dryRunEnv;

    if (!canPost) {
      console.log("✅ [DRY RUN] Tweet not sent to API");
      // return a fake id so threading logic continues during dry run
      return `dry_${Math.random().toString(36).substring(2, 8)}`;
    }

    // actual posting path
    const posted = await twitterClient.v2.tweet(tweetText, tweetData);
    console.log("✅ Tweet sent successfully!!");
    return posted.data.id; // return tweet ID for threading
  } catch (error) {
    console.error("❌ Error sending tweet:", error);
    return null;
  }
}

// --- Main runner ---
async function run() {
  try {
    // special mode for demonstration without calling Gemini
    if (process.env.SAMPLE) {
      console.log("🔧 SAMPLE mode enabled – using hardcoded tweets");
      const samplePosts = [
        "Stock of the Day 🚀\n\n** Sample Co **\n\nThis is test content describing the company. #Sample\n\nsee more ...",
        "Lets dive into detailed analysis -\n\n**Technicals:**\n- sample technical point.\n\n**Fundamentals:**\n- sample fundamental note.\n\n**Positives:**\n- none\n\n**Negatives:**\n- none\n\n**Outlook:** Neutral sample text."
      ];

      let replyToId = null;
      for (const tweet of samplePosts) {
        replyToId = await sendTweet(tweet, replyToId);
        if (!replyToId) break;
        await new Promise((r) => setTimeout(r, 500));
      }
      return;
    }

    const stock = getNextStock()
      .replace(/&amp;/g, "&")
      .replace(/\s+/g, " ")
      .trim();

    const threadPrompt = `
Generate a DAILY STOCK THREAD for X (Twitter).

Stock: ${stock}

Return output STRICTLY in this JSON format:
{
  "posts": [
    "First post text",
    "Second post text"
  ]
}

Very important rules (follow exactly):
- Produce exactly two posts in the 'posts' array.
- Post 1 (the teaser):
  - Start with the text \`Stock of the Day 🚀\` on its own line, followed by a blank line, then the stock name wrapped in double asterisks (\`** STOCK NAME **\`), another blank line, then the interesting content.
    - Maximum 270 characters total (including hashtags and the \`see more ...\` suffix).

  - One short 1–2 line insight that highlights something *very interesting* about the company (industry / product / unique catalyst).
  - Must include at least one relevant X hashtag (e.g. sector or company hashtag) after the insightful sentence.
  - Must end exactly with: 'see more ...' (three dots; the post string itself should end with that phrase).

- Post 2 (the deep dive):
  - Start the tweet with the line: \`Lets dive into detailed analysis -\` followed by two line breaks.
  - Investment-banking style summary. Include clear section headers exactly as shown below, with each header **bolded** (wrapped in \`**\`), and use short bullet points where appropriate.
  - Required sections (use these exact headings in bold):
    - \`**Technicals:**\`
    - \`**Fundamentals:**\`
    - \`**Positives:**\`
    - \`**Negatives:**\`
    - \`**Outlook:**\` (a single clear investor-style sentence)

Tone: professional, concise, investor-focused. Avoid hype and emojis.

Example posts content (for guidance):
{
  "posts": [
    "Stock of the Day 🚀\n\n** Example Corp **\n\nIndustry: Renewable components. Unique insight: large order backlog drives near-term earnings revisions. #Renewables see more ...",
    "Lets dive into detailed analysis -\n\n**Technicals:**\n- Trades with steady momentum, low volatility.\n\n**Fundamentals:**\n- Business: Manufactures X for Y.\n- Revenue model: Product sales + recurring service.\n\n**Positives:**\n- Long-term contracts\n- Strong balance sheet\n\n**Negatives:**\n- Supply chain exposure\n- Concentrated customer base\n\n**Outlook:** Favorable medium-term growth driven by infrastructure spending."
  ]
}

`;

    const raw = await generateTweet(threadPrompt);

    const cleaned = raw
      .replace(/```json/i, "")
      .replace(/```/g, "")
      .trim();

    // Escape unescaped control characters within quoted strings before parsing
    const fixed = cleaned.replace(/"([^"\\]|\\.)*"/g, (match) => {
      return match
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/\t/g, '\\t');
    });

    const parsed = JSON.parse(fixed);

    if (!parsed.posts?.length) {
      console.error("❌ No posts generated");
      return;
    }

    const safeTrim = (text, limit = 270) => {
      if (text.length <= limit) return text;
      // slice then trim last word; afterwards ensure suffix remains
      let trimmed = text.slice(0, limit).replace(/\s+\S*$/, "").trim();
      // if suffix got chopped off, reappend the full version
      if (/see more\s*\.\.\.?$/i.test(trimmed) && !/see more \.+$/i.test(trimmed)) {
        // ensure exactly three dots
        trimmed = trimmed.replace(/see more\s*\.\.*$/i, "see more ...");
      }
      return trimmed;
    };

    // Helpers to enforce required structure when model output is imperfect
    function makeHashtag(stockName) {
      // Use first 2-3 words or meaningful part (avoid "Limited", "Company", etc.)
      const stopwords = ['limited', 'company', 'corp', 'ltd', 'inc'];
      const parts = stockName.replace(/[^A-Za-z0-9 ]/g, "").split(/\s+/).filter(Boolean);
      let candidate = parts.slice(0, 2).join('');
      
      // If last word is a stopword and we have multiple words, drop it
      if (parts.length > 1 && stopwords.includes(parts[parts.length - 1].toLowerCase())) {
        candidate = parts.slice(0, -1).slice(-2).join('');
      }
      
      if (!candidate) candidate = stockName.replace(/[^A-Za-z0-9]/g, "");
      return `#${candidate.replace(/[^A-Za-z0-9]/g, "")}`;
    }

    function ensureFirstPostRules(text, stockName) {
      // Remove any existing headers/prefixes if present
      let t = text
        // strip any repeated header structures anywhere in the string
        .replace(/Stock of the Day\s*🚀[\s\S]*?\*\*[^*]+\*\*/gi, '')
        .replace(/\s+/g, " ")  // Normalize whitespace
        .trim();
      
      // Build final structure: header + content + hashtag + see more ...
      const header = `Stock of the Day 🚀\n\n** ${stockName.trim()} **\n\n`;
      const hashtag = makeHashtag(stockName);
      // hashtags and suffix on their own lines with extra spacing
      const suffix = `\n\n${hashtag}\n\nsee more ...`;
      
      // Remove any trailing see more or hashtags from content
      t = t.replace(/\s*see more\s*\.{0,3}\s*$/i, '').trim();
      t = t.replace(/\s*#\w+(\s+#\w+)*\s*$/i, '').trim();
      
      // Build final: header + content + suffix
      let result = header + t + suffix;
      
      // Enforce max length 270 by trimming body if needed
      if (result.length > 270) {
        // Reserve space for header and suffix
        const reserved = header.length + suffix.length;
        const maxBody = 270 - reserved;
        if (maxBody > 0) {
          let trimmed = t.slice(0, maxBody).replace(/\s+\S*$/, "").trim();
          result = header + trimmed + suffix;
        }
      }

      return result;
    }

    function ensureSecondPostSections(text) {
      // add prefix if missing
      let t = text;
      if (!/^Lets dive into detailed analysis/i.test(t)) {
        t = "Lets dive into detailed analysis -\n\n" + t;
      }
      const hasAllHeaders = /\*\*Technicals:\*\*|\*\*Fundamentals:\*\*|\*\*Positives:\*\*|\*\*Negatives:\*\*|\*\*Outlook:\*\*/i.test(t);
      if (hasAllHeaders) return t.replace(/\n{3,}/g, "\n\n").trim();

      // Heuristic splitting into sections if headers missing
      const sentences = t.replace(/\n+/g, " ").split(/(?<=[.!?])\s+/).map(s => s.trim()).filter(Boolean);
      const technical = sentences.slice(0, 1).join(' ');
      const fundamental = sentences.slice(1, 2).join(' ');
      const positives = sentences.slice(2, 4).map(s => `- ${s}`).join('\n') || '- N/A';
      const negatives = sentences.slice(4, 6).map(s => `- ${s}`).join('\n') || '- N/A';
      const outlook = sentences.length ? sentences[sentences.length - 1].replace(/[\n\r]/g, ' ').trim() : 'Neutral.';

      return `Lets dive into detailed analysis -\n\n**Technicals:**\n- ${technical}\n\n**Fundamentals:**\n- ${fundamental}\n\n**Positives:**\n${positives}\n\n**Negatives:**\n${negatives}\n\n**Outlook:** ${outlook}`;
    }

    // Only two posts expected; enforce limits and structural rules explicitly
    const finalPosts = parsed.posts.slice(0, 2).map((p, idx) => {
      const trimmed = p.replace(/\n{3,}/g, "\n\n").trim();
      if (idx === 0) {
        const enforced = ensureFirstPostRules(trimmed, stock);
        return safeTrim(enforced, 270);
      }
      // second post: ensure sections then optionally cap with a very large limit
      let enforced2 = ensureSecondPostSections(trimmed);
      // if Outlook header still missing after sectioning, append generic line
      if (!/Outlook:/i.test(enforced2)) {
        enforced2 += "\n\nOutlook: See above for key drivers and risks.";
      }
      // do not truncate aggressively; allow up to 2000 characters
      return safeTrim(enforced2, 2000);
    });

    console.log(`🧵 Posting ${finalPosts.length} tweets`);

    let replyToId = null;
    for (const tweet of finalPosts) {
      replyToId = await sendTweet(tweet, replyToId);
      if (!replyToId) break;

      // ⏳ critical: avoid X rate limits
      await new Promise(resolve => setTimeout(resolve, 30_000)); // 30 seconds
    }

  } catch (err) {
    console.error("❌ Thread generation failed:", err);
  }
}

run();
